name: 'Terraform - GitHub'

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/github/**'
      - '.github/workflows/terraform-github.yml'
  push:
    branches: [ main ]
    paths:
      - 'terraform/github/**'
      - '.github/workflows/terraform-github.yml'

defaults:
  run:
    working-directory: ./terraform/github
    shell: bash

jobs:
  terraform-github:
    name: 'Terraform GitHub'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        id: plan
        run: terraform plan

      - name: Comment Plan
        if: always() && steps.plan.outputs.stdout && github.ref != 'refs/heads/main'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Plan:
            
            https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}

            ```
            ${{ steps.plan.outputs.stdout }}
            ```

      - name: Terraform Graph
        if: github.ref != 'refs/heads/main'
        run: terraform graph

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
