name: 'Terraform - AWS'

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/github/**'
      - '.github/workflows/terraform-github.yml'
  push:
    branches: [ main ]
    paths:
      - 'terraform/github/**'
      - '.github/workflows/terraform-github.yml'

defaults:
  run:
    working-directory: ./terraform/github
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Format
        run: terraform fmt -check

  plan:
    name: 'Plan'
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Comment Plan
        if: github.ref != 'refs/heads/main'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Plan:
            
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/checks#step:5:1

            ```
            ${{ steps.plan.outputs.stdout }}
            ```

  apply:
    name: 'Apply'
    if: github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
